<?php

return [
    'NOTIFICATION_CATEGORY' => [
        'CART' => 1,
        'ORDER' => 2,
        'ECOM_ORDER' => 3,
        'ST1_ORDER' => 4,
        'ST2_ORDER' => 5,
        'ECOM_ORDER_ITEM_OUTOFSTOCK' => 6,
    ],
    'USER_CARD_STATUS' => [
        'ENABLED' => 1,
        'DISABLED' => 2,
    ],
    'CARD_TYPE' => [
        'DEFAULT' => 1,
        'OTHER' => 0,
    ],
    'NOTIFICATION_MESSAGE_TYPE' => [
        'CART_ADDED' => 100,
        'CART_DELETED' => 101,
        'ORDER_PLACED' => 200,
        'ORDER_CREATED' => 201,
        'ECOM_ORDER_STATUS_CHANGED' => 300,
        'ST1_ORDER_STATUS_CHANGED' => 301,
        'ST2_ORDER_STATUS_CHANGED' => 302,
        'ECOM_ORDER_ITEM_OUTOFSTOCK' => 303,
    ],
    'imageSize' => [
        'common' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
        ],
        'vendor' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'vendor/images',
        ],
        'store' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'store/images',
        ],
        'brand' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'brand/images',
        ],
        'category' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'category/images',
        ],
        'product' => [
            'width' => 360,
            'height' => 480,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'product/images',
        ],
        'banner1' => [
            'width' => 1920,
            'height' => 800,
            'aspectRatioW' => 1920,
            'aspectRatioH' => 800,
            'path' => 'banner/images',
        ],
        'banner2' => [
            'width' => 720,
            'height' =>379,
            'aspectRatioW' => 720,
            'aspectRatioH' => 379,
            'path' => 'banner/images',
        ],
        'banner3' => [
            'width' => 720,
            'height' =>379,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'banner/images',
        ],
        'categorybanner' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'banner/images',
        ],
        'serviceBanner' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'banner/images',
        ],
        'serviceProduct' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'serviceProduct/images',
        ],
        'generalClass' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'generalClass/images',
        ],
        'blogAuthor' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'blogAuthor/images',
        ],
        'vlogBlog' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'blog/images',
        ],
        'offerBrand' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'offerBrand/images',
        ],
        'offers' => [
            'width' => 640,
            'height' => 400,
            'aspectRatioW' => 640,
            'aspectRatioH' => 400,
            'path' => 'offers/images',
        ],
    ],
];
